/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.scala


import org.jooq.mcve.scala.tables.Test


/**
 * Convenience access to all tables in mcve.
 */
object Tables {

  /**
   * The table <code>mcve.test</code>.
   */
  def TEST = Test.TEST
}
