/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.mcve.java.tables.Test;
import org.jooq.mcve.java.tables.records.TestRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TestRecord> CONSTRAINT_2 = Internal.createUniqueKey(Test.TEST, DSL.name("CONSTRAINT_2"), new TableField[] { Test.TEST.ID }, true);
}
